### ISSUE TITLE
Some menus not functional using Oculus Rift controller

### ISSUE THREAD

**Issue by RobWed** [Odie/skyui-vr#59] opened 2021-11-14 03:16 UTC
Frostfall > Armour & Clothing
Select 'Type'
Opens a menu window where you should be able to select an armour slot and modify Frostfall warmth and coverage values.

One quadrant on either joystick will immediately go to the bottom of the list then no further observable action
Either Grip button will back out of this window.

Not able to select anything from the list.
Y and B buttons showing on the window do nothing.

I've tried adding options to controlmapvr.txt but I'm not knowledgeable enough to know what this particular menu is called

**Comment by Odie** [comment] 2021-11-14 03:29
Thanks for reporting this! 

Just to clarify, are you using this version of skyui?
https://github.com/angrmgmt/skyui-vr/releases

Also, which controller are you using? If you’re using the vive controller, does swiping behave any differently?

Lastly, do you mind posting a quick screenshot?

**Comment by RobWed** [comment] 2021-11-14 04:12
I'm using that patch at the end of the relevant section of my build.

My load order is:

SkyUIVR v1.1.0
<some other mods>
Campfire 1.12.1SEVR
Frostfall 3.4.1 SE
Campfire and Frostfall - Unofficial SSE Update
Campfire - Mortar and Pestle VR CTD Fix
Campfire Shrines
Hunterborn
Hunterborn SE MCM
Last Seed
SkyUIVR.and.Frostfall.Patch.v1.0F-beta.1
<the rest of the mods>

I'm using the Oculus Rift controllers.

Screenshot:
![Screenshot 2021-11-13 191927](https://user-images.githubusercontent.com/94270533/141667207-a01baf84-0834-4ef0-a798-0258c9658749.png)

**Comment by RobWed** [comment] 2021-11-14 04:15
That's not my entire load order btw. There are other mods before Campfire and more after SkyUIVR-Frostfall Patch
I think the editor window recognises html markup. Who knew?!

**Comment by RobWed** [comment] 2021-11-14 04:21
Also I did notice when testing my build that dropping SkyUIVR-Frostfall Patch and putting SkyUIVR v1.1.0 after the Campfire suite seemed to work fine.
 
 I would test this particular issue with that load order now but I'm having some difficulties loading SkyrimVR. SKSEVR is kicking of SkyrimVR.exe fine but the exe never progresses beyond a background process.

**Comment by RobWed** [comment] 2021-11-14 05:10
Okay I've resolved my problem accessing SkyrimVR. I believe it was MO2 failing to maintain its mod list properly.

I went back into the MCM menu and the menu you access with the little down triangle, as in where it says 'No Protection' in the screenshot, works in all other mod MCMs. It also works on all the similar menu choices within the Frostfall MCM except for the ones on this page.

Wouldn't that make it a problem with the MCM config script for Frostfall rather than a problem with SkyuiVR?

**Comment by Odie** [comment] 2021-11-14 05:38
The frostfall scripts likely just calls some MCM exposed feature that says "Let the user choose between these 5 choices". Showing the UI and handling controller input would be handled by MCM/Skyui.

It's strange that it would work for some screens but not work for this one. Lemme see if I can track this one down.

**Comment by Odie** [comment] 2021-11-14 06:16
After installing 
- Campfire 1.12.1SEVR
- Frostfall 3.4.1 SE
- Campfire and Frostfall - Unofficial SSE Update
- SkyUIVR.and.Frostfall.Patch.v1.0F-beta.1

I can also confirm that the UI doesn't seem to be responding much. What *is* the intended behavior there? Should I be able to scroll up and down and make a selection there?

**Comment by Odie** [comment] 2021-11-14 07:13
Yeah, this looks like a bug.

Looks if an item isn't already selected, then trying to move up and down has no effect. But once an item has been moused over, then things start working again.

I'll try to fix this and hopefully roll this out along with a larger update in a few days. In the meantime, you can get around this by using the [VR mouse fix](https://www.nexusmods.com/skyrimspecialedition/mods/33414).

**Comment by RobWed** [comment] 2021-11-14 08:52
Great! Thanks Odie! It'd be great to make mod armours frostfall aware.

Wish I could help but I know nothing of Papyrus and was never a developer.

**Comment by Odie** [comment] 2021-11-14 09:09
Just leaving a technical note here for maybe future reference:

I think this might actually be a bug that's in the current version of SKSE:
https://github.com/Odie/sksevr-mirror/blob/5968056e4bef849b4f506fa42393d0f3d3cf6225/skse64/PapyrusUI.cpp#L18

What happens is, a mod author can setup a menu from Papyrus. He may or may not set a startIndex for the menu. If he doesn't the value defaults to -1. When it's passed through SKSE to be sent to Scaleform (the UI), the signed integer -1 passed, but isn't correctly converted to the expected double precision float. So by the time the UI code gets the number, it is read as 4294967295 (that's 0xffffffff, or -1 signed int).

Since I can't update SKSE or get everyone to install a patched version, the next thing to do is to simply check for this special value in the UI code and reinterpret that as -1.

**Comment by Odie** [comment] 2021-11-14 13:36
Can you try this out for me? This patches a minor bug that causes this particular problem and hopefully solves a whole class of problems that stems from not being able to send negative numbers from Papyrus => Scaleform.

[SkyUI - MCM OptionsMenu fix.zip](https://github.com/Odie/skyui-vr/files/7533820/SkyUI.-.MCM.OptionsMenu.fix.zip)

**Comment by RobWed** [comment] 2021-11-14 21:50
Okay, I'll try it now.

**Comment by Odie** [comment] 2021-11-15 05:52
Hmm!

With the fixed version I posted above, when you bring up the option menu, it should still look like the screenshot you posted above, with nothing highlighted. I took a peek at the frostfall scripts, and that seems to be the way it's authored, to have nothing highlighted by default. What's different though, is you should be able to hit the "down" button to have the first item highlighted. From there, the menu should work normally.

**Comment by RobWed** [comment] 2021-11-15 21:43
Yes that's what it looks like. Nothing highlighted. However the only controller function is as before:

> One quadrant on either joystick will immediately go to the bottom of the list then no further observable action
Either Grip button will back out of this window.

Passing the mouse cursor over the menu window effectively does what you hoped the down button would so from my perspective this has moved from a blocker to a minor inconvenience. I'm still happy to continue testing if you've got wider concerns.

**Comment by RobWed** [comment] 2021-11-16 03:15
Actually, I just noticed this in MO2:

You have one or more script extender plugins which failed to load!

The failed plugins are:
  • Couldn't load SkyUI-VR.dll (SkyUI). A dependency DLL could not be found (code 126).

**Comment by Odie** [comment] 2021-11-16 03:54
Okay. The fix is implemented in the DLL, which patches around a SKSE bug to make the UI work as intended. If the DLL isn't loading, I can see why things aren't working for you then.

Lemme see if I figure out what might be causing that.

**Comment by RobWed** [comment] 2021-11-16 06:41
Yeah I loaded 1.1.0 and didn't have a problem with the DLL

**Comment by Odie** [comment] 2021-11-16 07:01
I think the problem was that I built it in debug mode, which will also ask for other debug-related DLLs that are not usually installed on people's machines. Here's a version built in release mode. Hopefully, this will get loaded without issues.

[SkyUI - MCM OptionsMenu fix 2.zip](https://github.com/Odie/skyui-vr/files/7543981/SkyUI.-.MCM.OptionsMenu.fix.2.zip)

Assuming the DLL loads, if this still doesn't work, please do send me the skse log. =)

**Comment by RobWed** [comment] 2021-11-17 02:14
Okay, that works perfectly!

Thanks for your time on this!

Will this get merged into the main branch?

And will the Frostfall patch get merged into main?

**Comment by Odie** [comment] 2021-11-17 02:22
Great! Thanks for testing things out.

Yes, this will get merged into the main branch. I’ll make a release later today along with some other features.

I’m not entirely sure how to deal with the frostfall patch, honestly. Although there aren’t drastic changes, it does chang both code and layout. I’m not sure how that can be easily integrated into the same codebase. =(

**Comment by Odie** [comment] 2021-11-17 10:42
The fix has been released as a part of v1.2.0.
:)

**Closed by Odie** 2021-11-17 10:42 UTC
