### ISSUE TITLE
UI freeze at enchanting table

### ISSUE THREAD

**Issue by DimkaAkuma** [Odie/skyui-vr#12] opened 2018-10-01 20:49 UTC
Issue with UI freezing when enchanting weapons 
 first I  mark  weapon i wish to enchant
 second I mark Petty Soulgem (the ones i have atm)
 third I mark any enchantment that later has to be tweaked in terms charges/power, and when I try to go all the way left (more charges and less power) UI freezes.

**Comment by Odie** [comment] 2018-10-07 06:41
Alrighty. Will look into this. =)

**Comment by Odie** [comment] 2018-10-10 03:09
Hmm... I cannot reproduce this with the latest release. Which version are you running?

**Comment by Odie** [comment] 2018-10-12 06:38
Yikes... these are the scariest kinds of bugs. It *sometimes* happen on for *some* users *some* of the time.

So, just to be clear. Workbenches usually work, except for the ones in the Morthal manor?

I'll try the super fast storage clicking problem. That's definitely a showstopper. I have no idea what might be causing these issues. I think the only menu that doesn't currently have an input speed limiter already is the player inventory menu. IIRC, all other menus are set to respond only if the event is at least 10ms apart.

In any case, I'll try reproducing these problems tomorrow. Will keep everyone up to date here.

**Comment by Odie** [comment] 2018-10-13 06:19
Alrighty. So after messing around with the game for an hour or so at the Windstad. I still cannot reproduce either of the reported issues. 

I'm going to leave this one open for a bit longer. But I really can't do anything to fix the bugs if I can't reproduce them. Maybe someone else will come along and figure out the exact conditions where this happens. 

In the meantime, please do make sure you're using the latest version.
Thanks again for reporting the bug.

**Comment by darknessneo** [comment] 2018-10-13 13:44
https://youtu.be/vLvCXSYcfVg here is a exemple about my freeze. Im using trackpad 1 and 2 for be more fast. When i have a stack +6 i use trigger without stop using trackpads. Sometimes i got a freeze where i can't do anything else than close the container. At the end, i go back to the steam menu by mistake (cuz i was hiting on all button like hell) and when i was back to container menu, i just freeze it totaly. All other time i can close it but not here, impossible to do anything else than open steam menu. When i close it, im on the game menu where i can check quest, see stat or loading/save/leave the game. This menu work, but when i closed it for back to container, nothing again. hope that help u. Anyway, i deal with it, i make that bug anytime i wan stock my alchemist's items, and when i dont make a mistake (uhuh) i close the container and repeat again, i dont care about that.

**Comment by Odie** [comment] 2018-10-14 02:38
Thanks for the video!
Looks like it’s happening very often for you. :(

Just to put things into words... it looks like the UI froze at around 0:25 in the video, right after you placed 4 items in a large stack into the container.

Will go try this out.

**Comment by Odie** [comment] 2018-10-14 16:59
Howdy!

I've had a bit more luck reproducing the bug by smashing randomly on the controller. I *think* it's fixed. Please help me verify if this fixes the issue or not.

[SkyUI - VR - container freeze fix.zip](https://github.com/Odie/skyui-vr/files/2476637/SkyUI.-.VR.-.container.freeze.fix.zip)

There are only 2 files in this zip file. Please just override the existing skyui files.

Thanks!

**Comment by darknessneo** [comment] 2018-10-14 18:00
tested! More stable than before ^^ i can still freeze the container, but not all the time. Already a nice works about the fix ^^ (full alchimic item: only 2 freezes that needed to close the container), trust me, its realy better than before for me, but im a crazy controler user :D 
Now i remember a think about oldrim version, container had already a thing like that, I always was a crazy item stocker. In oldrim, skyui just remove the item selector cursor and i needed to scroll down again for do my stuff.
but ofc, i never got a freeze from oldrim. So finaly, ur fix its like the oldrim version ^^ great job anyway, im already happy to have a working skyui version for VR 👍

**Comment by Odie** [comment] 2018-10-14 18:08
Alrighty. At least it’s an improvement. It’s really strange that I’ve never encountered container freezes before.

What about crafting stations? You mentioned you encountered freezes there also. Is this something that happens a lot? Do you think you might be able to capture some footages of this happening?

**Comment by darknessneo** [comment] 2018-10-14 18:37
https://youtu.be/1PWR7sUW3XQ workbench make me crazy!! see that and enjoy my secretary ^^
i think i dont need to explain :DD

**Comment by Odie** [comment] 2018-10-15 06:09
From your video, I see what the workbench menu sometimes comes up empty. Is that the issue you're talking about?

I tried the same thing at Windstad but I cannot get this to happen. I tried smashing on the controller buttons, but still no luck.

**Comment by darknessneo** [comment] 2018-10-15 10:56
disabled skyui for check by myself. Sound like i have a mod that bug workbench stations. Dont know what mod do that cuz i dont moded HF houses, false alarm anyway ^^' but this bug is annoying hehe sry about that

**Comment by Odie** [comment] 2018-10-15 11:01
@darknessneo Alrighty. No worries. =)

@DimkaAkuma are you still having issues with the enchant menu? Since I can’t reproduce your specific issue, I’m going to close this for now.

**Closed by Odie** 2018-10-15 11:01 UTC
Labels: cannot-reproduce, priority/high
