### ISSUE TITLE
Impossible to loot object with HP Reverb G2

### ISSUE THREAD

**Issue by Shuumi** [Odie/skyui-vr#65] opened 2021-12-04 10:19 UTC
When looting a corpse no button can be mapped to pick up an object.
I am using a HP Reverb G2 motion controller.

All buttons on this controller in an inventory screen either do nothing, equip/consume, search or close the menu. No other action is possible. Picking up an object, as well as adding an item/spell to favorites are not possible.

I also created my own mapping through Steam VR's "Controller Binding" and went through every possible action, but could not find any that picks up an object. I worked out that all of the actions labeled "east", "west", "north", "south" and "Trackpad/Thumbstick Press" for both controllers start a search.

On the in-game UI, the Icon shows that only the "south" action should start a search.

**Comment by Shuumi** [comment] 2021-12-04 10:24
I see you are already on the issue with WMR controllers. I think this will fix my problem too. Consider this a duplicate

**Comment by Odie** [comment] 2021-12-04 10:59
Yeah, proper WMR support should be coming soon. =)

**Comment by Odie** [comment] 2021-12-04 11:00
Duplicate of #64. Closing for now.

**Closed by Odie** 2021-12-04 11:00 UTC
Labels: duplicate

**Comment by Odie** [comment] 2021-12-06 15:23
Hi there!

A version has just been [released](https://github.com/Odie/skyui-vr/releases/tag/v1.2.1)! Hopefully, it fixes the problem you've been experiencing.

Please do let me know if there are any problems!
