### ISSUE TITLE
Cant drop anything wmr controllers

### ISSUE THREAD

**Issue by RiverBloodWolf** [Odie/skyui-vr#64] opened 2021-11-27 02:35 UTC
So I downloaded everything correctly but my skyui vr menu won't let me drop things. When I press the button (left on touchpad) it pops up the search bar. The search is binded to all of my TouchPad for some reason and now I cant drop or pick up items. I've tried to unbind it, however it will only let me bind it to a different button on my keyboard not my controller

**Comment by Odie** [comment] 2021-11-27 04:31
Hi there!

Sorry you've having trouble with this. I was only able to test this with the vive controller. Unfortunately, there is no way to rebind the key right now at the moment. I'll try to implement something soon though!

Thanks for bringing this up!

**Comment by tsteinmetz27** [comment] 2021-11-27 04:57
I'm also having a similar issue. With the WMR controllers, when in a container the only way to take items is with LT or RT which then equips or uses them (which makes trying to loot potions impossible). The buttons for 'Take' and 'Take All' don't work as the entire touchpad seems to be taken up by the search function as the OP mentioned. Please update if there are any developments because I love the changes that SkyUI adds and would like to be able to use it properly.

**Comment by MaxxJag** [comment] 2021-11-29 03:21
Count me in as having this issue. I'll see if I can understand how this works.

**Comment by iEx5** [comment] 2021-11-29 22:23
Same problem here,
I guess it better to use a hold system button for a 2-3 sec if it's possible...

**Comment by Odie** [comment] 2021-11-30 00:45
So what are the buttons that are currently unused in the various inventory type menu screens?

Let me see if I can put something in quickly.

**Comment by tsteinmetz27** [comment] 2021-11-30 02:54
Start/options button is unused as far as I know. I think everything else off of the touchpad is used.

**Comment by Odie** [comment] 2021-11-30 04:03
Alrighty, I'll need help from you guys. There are a few pieces of info I need to get this implemented. 

## The Goal
OpenVR will report something like "button number 5 has been pressed". But, without knowing which button on your controller is "button number 5", it's impossible to put in rules like "when the menu button is pressed, do this".

I need your help to figure out which button correspond to what number.


## Turning on the debug feature
v1.2 actually has a hidden feature that can be turned on to help figure this out. To enable this feature, please do the following:

You'll find a file packed with skyui: "SKSE\Plugins\Skyui-VR.ini.SAMPLE", remove the ".SAMPLE". Then open up the file and change set "showInputReadout" to "true".


## How to interpret the output
Once the feature is turned on, when you get into the quest journal menu, there should be a strange-looking panel to the right that shows the button(s) OpenVR says has been touched/pressed/clicked.

It'll look something like this:
![ControllerInfo](https://user-images.githubusercontent.com/10692/143983207-db5e91be-49f0-4665-8ce1-c760e24fa6a9.png)

In this particular screenshot, skyUI is reporting this:
```
Something numbered 0 and 32 has been touched.
x[0] and y[0] is reporting some value.
```

## Please report the following
For each button/joystick/touchpad you have on the controller, please press it and note down:
```
Which "number" reports being touched/pressed
Which axis reports useful values (example: x[0], y[0] or x[1])
```

Once I have these mappings, I should be able to put in the changes for you guys to try out.

**Comment by tsteinmetz27** [comment] 2021-12-01 16:45
Did a quick test with this to see which buttons I could figure out. As far as I could tell, in all cases the readout showed the button number marked as 0 and another number, so I am only including the other number below. Additionally, I wasn't sure if there was a way to switch the readout to the right controller (or if the right controller would even read different values) so these values shown are all from the left controller. Here is what I got:

- Left Trigger reads 33. Can be touched or pressed. Touched is any point up to full compression, pressed is only at full compression.
- The Start/Menu button reads 1. Can only be pressed as far as I could tell.
- The entire touchpad reads 32. It can be touched or pressed, and moved in several directions. It registered as touching the touchpad when only setting a finger on a particular area, and pressing when actually clicking the button at a particular point. As for the axes, it appeared to read similarly to a normal plot, where the center read x and y close to zero, touching or pressing the right side read x close to 1 and y close to zero, touching or pressing the top of the touchpad read x close to 0 and y close to 1 and so on.
- The analog stick reads 34. It can only be touched (actually pressing in on the analog stick opens up the Steam overlay). The axes read out in the exact same way as the touchpad. 
- I was not able to get a value for the rear grip button as it is the button that closes menus, so pressing it would close the readout screen. As far as I could tell, it cannot be touched, only pressed. I would assume based on the numbering of the other buttons that it is either 31 or 35. 
- The windows button did not display any readout whatsoever as it opens up the Windows Mixed Reality control panel. 

One thing I noticed while doing this is that it is really easy to fat-finger the touchpad and have it read a press in a quadrant that I wasn't intending. As a result of this, if it is at all possible, it would be ideal to have any functions on the touchpad separated by at least one region (i.e. left is take, center is search, and right is take all as opposed to having left as take and down as take all, in which case you may accidentally take all when you mean to only take one item.)

**Comment by Odie** [comment] 2021-12-02 03:09
Thanks for the detailed info! Time for me to get to work!

> One thing I noticed while doing this is that it is really easy to fat-finger the touchpad

Another thing I can try doing is to give it a bit of a gap between the regions/quadrants, so it you accidentally click outside a region, it just doesn’t do anything, instead of registering as a click in the neighbor region.

**Comment by butrejp** [comment] 2021-12-02 04:41
I have the same issue with the latest version.  1.1.0 is working fine for now.

**Comment by Odie** [comment] 2021-12-03 07:26
> * The entire touchpad reads 32.
> * Left Trigger reads 33.
> * The analog stick reads 34.

With these 3 widgets, can you also check which "axis" is reporting data when they are touched/pressed? What I mean is, besides reporting there is data on x and/or y, it would also report *which* xy axis the data is being reported on:
```
This number
   v
x[0] = 0.283495
y[0] = 01203
```

Ideally, these 3 widgets would all be reporting data on a different set of axis. For example, maybe the touchpad is reporting on x[0], y[0], whereas the analog stick would be reporting on x[1], y[1]. The trigger might be reporting on x[2].

Thanks!

**Comment by alandtse** [comment] 2021-12-04 21:59
Let me know if you want a new issue, but this impacts the Quest 2 folks in our ability to zoom on items like Claws. We use right thumbstick click. Here's the button click info.
```
32
x[0]
y[0]
```

**Comment by Odie** [comment] 2021-12-04 22:57
> Let me know if you want a new issue, but this impacts the Quest 2 folks in our ability to zoom on items like Claws. We use right thumbstick click. Here's the button click info.

Okay! I’ll push out a fix for the Quest sometime today.

**Comment by tsteinmetz27** [comment] 2021-12-05 00:20
From what I can tell, the touchpad reads on axis [0], the trigger reads on axis [1] and the analog stick reads on axis [2].

**Comment by Odie** [comment] 2021-12-05 02:21
> From what I can tell, the touchpad reads on axis [0], the trigger reads on axis [1] and the analog stick reads on axis [2].

Awesome! Thanks for this!

**Comment by Odie** [comment] 2021-12-05 16:07
Hi all!

Here's a hastily put together [test version](https://github.com/Odie/skyui-vr/files/7656317/SkyUI.-.configurble-actions.zip).

- WMR


  It *should* respond to the "application menu" button on every menu to initiate search.
  
- Quest 2
  It *should* respond to thumbstick presses on the left controller only.

I can't verify this very well on my end since I don't have these controllers. Please try it out and let me know how things go for you.

Thanks!

**Comment by MaxxJag** [comment] 2021-12-06 05:10
Works great on my WMR (Samsung Odyssey+)

**Comment by alandtse** [comment] 2021-12-06 10:36
> * Quest 2
>   It _should_ respond to thumbstick presses on the left controller only.

Confirmed it works as described.

**Comment by Odie** [comment] 2021-12-06 15:21
Hi all,

A slightly cleaned-up version has just been [released](https://github.com/Odie/skyui-vr/releases/tag/v1.2.1)!

Please do let me know if there are any problems!

**Closed by Odie** 2021-12-06 15:21 UTC
